apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: vuefront
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app: vuefront
        tier: frontend
    spec:
      containers:
        - name: vuevue
          image: bukanebi/jenkins:master
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: vuefront
    tier: frontend
  # type: LoadBalancer
  # type: ClusterIP
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      protocol: TCP
      name: frontendport

