---
apiVersion: v1
kind: Namespace
metadata:
  name: example

---
apiVersion: v1
data:
  PGHOST: "3.86.88.152"
  PGUSER: "bukanebi"
  PGDATABASE: "sample"
  PGPASSWORD: "bukanebi"
  PGPORT: "5432"
  SERVICEPORT: "9000"
  MODE: "Dev"

kind: ConfigMap
metadata:
  name: test-service
  namespace: example

--- 

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-rollout
  namespace: example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sampleapp
  template:
    metadata:
      labels:
        app: sampleapp
    spec:
      containers:
      - name: navbar
        image: karthequian/helloworld:black
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: test-service

---
apiVersion: v1
kind: Service
metadata:
  name: sample-rollout
spec:
  selector:
    app: sampleapp
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      nodePort: 30589
      protocol: TCP
      name: navservice